    <?php
    define('HOME_PATH', 'http://localhost/mikrotik/');
    $menu =     '<!-- START PAGE SIDEBAR -->';
    $menu .=    '<div class="page-sidebar">';
    $menu .=    '<!-- START X-NAVIGATION -->';
    $menu .=    '<ul class="x-navigation">';
    $menu .=    '<li class="xn-logo">';
    $menu .=    '<a href="inicio">DEMOTIK</a>';
    $menu .=    '<a href="#" class="x-navigation-control"></a>';
    $menu .=    '</li>';
    $menu .=    '<li class="xn-profile">';
    $menu .=    '<div class="profile">';
    $menu .=    '<div class="profile-data">';
    $menu .=    '<div class="profile-data-name"></div>';
    $menu .=    '<div class="profile-data-title"></div>';
    $menu .=    '</div>';
    $menu .=    '</div>';
    $menu .=    '</li>';
    $menu .=    '<li class="active">';
    $menu .=    '<a href="inicio"><span class="fa fa-desktop"></span> <span class="xn-text">Inicio</span></a>';
    $menu .=    '</li>';
    $menu .=    '<li class="xn-openable">';
    $menu .=    '<a href="#"><span class="fa fa-files-o"></span> <span class="xn-text">Generales</span></a>';
    $menu .=    '<ul>';
    $menu .=    '<li><a href="libreta_virtual"><span class="fa fa-users"></span> Libreta virtual</a></li>';
    $menu .=    '<li><a href="documentos"><span class="fa fa-file"></span> Documentos</a></li>';
    $menu .=    '<li><a href="anexos"><span class="fa fa-file"></span> Anexos</a></li>';
    $menu .=    '</ul>';
    if ($solo_NOC) {
    $menu .=    '</li>';
    $menu .=    '<li class="xn-openable active">';
    $menu .=    '<a href="#"><span class="fa fa-sitemap"></span> <span class="xn-text">Gesti&oacute;n Mikrotiks</span></a>';
    $menu .=       '<ul>';
    $menu .=            '<li class="xn-openable">';
    $menu .=            '<a href="#">General</a>';
    $menu .=                '<ul>';
    $menu .=                    '<li class="xn-openable">';
    $menu .=                    '<a href="interfaces">Interfaces</a>';
    $menu .=                    '</li>';
    $menu .=                    '<li class="xn-openable">';
    $menu .=                    '<a href="salud">Salud</a>';
    $menu .=                    '</li>';
    $menu .=                    '<li class="xn-openable">';
    $menu .=                    '<a href="buscar">Buscar En LOG</a>';
    $menu .=                    '</li>';
    $menu .=                '</ul>';
    $menu .=            '</li>';
    $menu .=        '</ul>';
    $menu .=       '<ul>';
    $menu .=            '<li class="xn-openable">';
    $menu .=            '<a href="#">Reportes</a>';
    $menu .=                '<ul>';
    $menu .=                    '<li class="xn-openable">';
    $menu .=                    '<a href="reportes/usuarios_userman">Clientes PPPoE</a>';
    $menu .=                    '</li>';
    $menu .=                    '<li class="xn-openable">';
    $menu .=                    '<a href="reportes/usuarios_queues">Clientes Por Colas Simples</a>';
    $menu .=                    '</li>';    
    $menu .=                    '<li class="xn-openable">';
    $menu .=                    '<a href="reportes/detalles_address_list">Address List</a>';
    $menu .=                    '</li>';
    $menu .=                    '</li>';    
    $menu .=                    '<li class="xn-openable">';
    $menu .=                    '<a href="reportes/usuarios_hotspot">Usuarios Hotspot</a>';
    $menu .=                    '</li>';
    $menu .=                '</ul>';
    $menu .=            '</li>';
    $menu .=        '</ul>';
    $menu .=       '<ul>';
    $menu .=            '<li class="xn-openable">';
    $menu .=            '<a href="#">Crear Usuarios</a>';
    $menu .=                '<ul>';
    $menu .=                    '<li class="xn-openable">';
    $menu .=                    '<a href="crear/crear_usuario_pppoe">Crear Cliente PPPoE</a>';
    $menu .=                    '</li>';
    $menu .=                    '<li class="xn-openable">';
    $menu .=                    '<a href="crear/crear_usuario_queue">Crear Cliente Queue</a>';
    $menu .=                    '</li>';
    $menu .=                '</ul>';
    $menu .=            '</li>';
    $menu .=        '</ul>';
    $menu .=       '<ul>';
    $menu .=            '<li class="xn-openable">';
    $menu .=            '<a href="#">Editar Usuarios</a>';
    $menu .=                '<ul>';
    $menu .=                    '<li class="xn-openable">';
    $menu .=                    '<a href="editar/editar_usuario_queue">Editar Usuarios Queues</a>';
    $menu .=                    '</li>';
    $menu .=                    '<li class="xn-openable">';
    $menu .=                    '<a href="crear/crear_usuario_queue">Crear Cliente Queue</a>';
    $menu .=                    '</li>';
    $menu .=                '</ul>';
    $menu .=            '</li>';
    $menu .=        '</ul>';
    $menu .=     '</li>';
    } else {
    }
    $menu .=    '</ul>';
    $menu .=    '<!-- END X-NAVIGATION -->';
    $menu .=    '</div>';
    $menu .=    '<!-- END PAGE SIDEBAR -->';

    $salir = HOME_PATH."action/logout.php";
    ?>